exports.home = home

// File List HTML Page Template  -----------------------------------------
function home( files, d){
    let pagHTML = `
      <html>
          <head>
              <title>File List</title>
              <meta charset="utf-8"/>
              <link rel="icon" href="/favicon.png"/>
              <link rel="stylesheet" href="/style.css"/>
          </head>
          <body>
            <div class="section">
                <div class="section-title">
                    <h2>FILE UPLOAD</h2>
                </div>
                <form action="/files" method="POST" enctype="multipart/form-data">
                    <label class="file-upload">
                        Select file
                        <input type="file" name="myFile" required>
                    </label>
                    <label><b>DESCRIPTION</b></label>
                    <textarea name="myDescription" rows="3" cols="30" required></textarea>

                    <input type="submit" value="Submit"/>
                </form>
            </div>
            <div class="section">
                <div class="section-title">
                    <h2>FILE LIST</h2>
                </div>
                <table>
                    <tr>
                        <th>DATE</th>
                        <th>FILE</th>
                        <th>DESCRIPTION</th>
                        <th>SIZE</th>
                        <th>TYPE</th>
                    </tr>
    `
    files.forEach( f => {
      pagHTML += `
          <tr>
              <td>${f.date}</td>
              <td>${f.name}</td>
              <td>${f.description}</td>
              <td>${f.size}</td>
              <td>${f.mimetype}</td>
          </tr>
      `
    })
  
    pagHTML += `
          </table>
          </div>
          <div class="footer">
              <address>Generated by myapp::RPCW2022 em ${d} --------------</address>
          </div>
      </body>
      </html>
    `
    return pagHTML
  }
